"""A watch tower for quiet standards.

iiRDS, VDI 2770 and the AAS submodels move slowly and announce quietly —
a new template directory here, a spec release there, a funding call that
opens for eight weeks. The people affected are exactly the people who do
not refresh eight pages daily. So a cron does: every source is diffed
against committed state, anything new becomes an event, and events become
a feed (feed.xml) and a human page (WATCH.md).

Standard library only, on purpose: a watcher that needs a dependency
update is a watcher that eventually stops watching.
"""
from __future__ import annotations

import hashlib
import json
import os
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent
MAX_EVENTS = 300
SHOWN_IN_MD = 40
SHOWN_IN_FEED = 50


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def fetch(url: str, accept: str = "application/vnd.github+json") -> bytes:
    request = urllib.request.Request(url, headers={
        "User-Agent": "standards-watch (github.com/dev365code/standards-watch)",
        "Accept": accept,
    })
    token = os.environ.get("GITHUB_TOKEN")
    if token and "api.github.com" in url:
        request.add_header("Authorization", "Bearer " + token)
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


# -- fetchers: each returns a list of (id, title, url) ----------------------

def fetch_gh_releases(repo: str):
    data = json.loads(fetch("https://api.github.com/repos/%s/releases?per_page=10" % repo))
    return [(str(r["id"]), "%s: %s" % (repo, r.get("name") or r["tag_name"]),
             r["html_url"]) for r in data]


def fetch_gh_dir(repo: str, path: str):
    data = json.loads(fetch("https://api.github.com/repos/%s/contents/%s" % (repo, path)))
    return [(entry["name"], "new template: %s" % entry["name"], entry["html_url"])
            for entry in data if entry["type"] == "dir"]


def fetch_gh_issues(repo: str, since: str):
    url = ("https://api.github.com/repos/%s/issues?state=all&sort=updated"
           "&direction=desc&per_page=30&since=%s" % (repo, since))
    data = json.loads(fetch(url))
    return [(("%s#%s@%s" % (repo, item["number"], item["updated_at"])),
             "%s#%d %s" % (repo.split("/")[1], item["number"], item["title"]),
             item["html_url"]) for item in data]


def fetch_html_hash(url: str) -> str:
    return hashlib.sha256(fetch(url, accept="text/html")).hexdigest()


# -- the pure part: state + fetched -> events (this is what the test holds) --

def diff_seen(state: dict, fetched, label: str, today: str):
    """Set-diff kinds. First sight seeds silently: a tower that fires 300
    'new' events on day one has taught its readers to ignore it by day two."""
    seen = set(state.get("seen", []))
    events = []
    if seen:
        for item_id, title, url in fetched:
            if item_id not in seen:
                events.append({"date": today, "source": label, "title": title, "url": url})
    state["seen"] = sorted(seen | {item_id for item_id, _t, _u in fetched})[-500:]
    return events


def diff_hash(state: dict, digest: str, label: str, url: str, today: str):
    events = []
    if state.get("hash") and state["hash"] != digest:
        events.append({"date": today, "source": label,
                       "title": "page changed — worth a look", "url": url})
    state["hash"] = digest
    return events


# -- outputs -----------------------------------------------------------------

def write_watch_md(sources, state, events):
    lines = ["# What moved",
             "",
             "Auto-generated by [watch.py](watch.py) on a daily cron; newest first.",
             "Subscribe via [feed.xml](feed.xml) in any RSS reader.",
             "", "## Latest", ""]
    if events:
        for event in events[:SHOWN_IN_MD]:
            lines.append("- **%s** · [%s](%s) · %s" % (
                event["date"][:10], event["title"], event["url"], event["source"]))
    else:
        lines.append("- (baseline established; events appear as the world moves)")
    lines += ["", "## Watched sources", "",
              "| source | kind | last checked |", "|---|---|---|"]
    for source in sources:
        checked = state.get(source["key"], {}).get("checked", "—")
        lines.append("| %s | %s | %s |" % (source["label"], source["kind"], checked[:16]))
    (ROOT / "WATCH.md").write_text("\n".join(lines) + "\n", "utf-8")


def write_feed(events):
    items = []
    for event in events[:SHOWN_IN_FEED]:
        items.append(
            "<item><title>%s</title><link>%s</link><pubDate>%s</pubDate>"
            "<description>%s</description></item>"
            % (escape(event["title"]), escape(event["url"]),
               event["date"], escape(event["source"])))
    feed = ("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            "<rss version=\"2.0\"><channel>"
            "<title>standards-watch: iiRDS / VDI 2770 / AAS</title>"
            "<link>https://github.com/dev365code/standards-watch</link>"
            "<description>Releases, templates, issue activity and funding "
            "calls around industrial documentation standards.</description>"
            + "".join(items) + "</channel></rss>\n")
    (ROOT / "feed.xml").write_text(feed, "utf-8")


def main() -> None:
    sources = json.loads((ROOT / "sources.json").read_text("utf-8"))["sources"]
    state_path = ROOT / "state.json"
    state = json.loads(state_path.read_text("utf-8")) if state_path.exists() else {}
    today = now_iso()
    fresh = []

    for source in sources:
        entry = state.setdefault(source["key"], {})
        try:
            if source["kind"] == "gh_releases":
                fresh += diff_seen(entry, fetch_gh_releases(source["repo"]),
                                   source["label"], today)
            elif source["kind"] == "gh_dir":
                fresh += diff_seen(entry, fetch_gh_dir(source["repo"], source["path"]),
                                   source["label"], today)
            elif source["kind"] == "gh_issues":
                since = entry.get("checked", today)
                fresh += diff_seen(entry, fetch_gh_issues(source["repo"], since),
                                   source["label"], today)
            elif source["kind"] == "html":
                fresh += diff_hash(entry, fetch_html_hash(source["url"]),
                                   source["label"], source["url"], today)
        except Exception as error:                          # noqa: BLE001
            # A dead source must not kill the tower; it shows up as a stale
            # "last checked" in the table instead, which a reader can see.
            print("skip %s: %s" % (source["key"], error))
            continue
        entry["checked"] = today

    events = (fresh + state.get("_events", []))[:MAX_EVENTS]
    state["_events"] = events
    state_path.write_text(json.dumps(state, indent=1, sort_keys=True) + "\n", "utf-8")
    write_watch_md(sources, state, events)
    write_feed(events)
    print("events: %d new, %d kept" % (len(fresh), len(events)))


if __name__ == "__main__":
    main()
